### ISSUE TITLE
Compilation Error with Julia 0.6

### ISSUE THREAD

**Issue by AsileBcd** [JuliaGraphs/GraphPlot.jl#38]
GraphPlot does not precompile properly on my computer (Windows 10 and Julia 0.6). It used to work with 0.5.2. Here is the error, it seems to be linked to the Graphs.jl dependency.

```julia
ERROR: LoadError: LoadError: TypeError: Type{...} expression: expected UnionAll, got base.Collections.#PriorityQueue  
Stacktrace:    
[1] include_from_node1(::String) at .\loading.jl:569  
[2] include(::String) at .\sysimg.jl:14 
[3] include_from_node1(::String) at .\loading.jl:569 
[4] include(::String) at .\sysimg.jl:14  
[5] anonymous at .\<missing>:2 
while loading C:\Users\bouac\.julia\v0.6\Graphs\src\maximum_adjacency_visit.jl, in expression starting on line 15 
while loading C:\Users\bouac\.julia\v0.6\Graphs\src\Graphs.jl, in expression starting on line 140 
ERROR: LoadError: Failed to precompile Graphs to C:\Users\bouac\.julia\lib\v0.6\Graphs.ji. 
Stacktrace:     
[1] compilecache(::String) at .\loading.jl:703   
[2] _require(::Symbol) at .\loading.jl:456  
[3] require(::Symbol) at .\loading.jl:398  
[4] include_from_node1(::String) at .\loading.jl:569 
[5] include(::String) at .\sysimg.jl:14  
[6] anonymous at .\<missing>:2
while loading C:\Users\bouac\.julia\v0.6\GraphPlot\src\GraphPlot.jl, in expression starting on line 7  
ERROR: Failed to precompile GraphPlot to C:\Users\bouac\.julia\lib\v0.6\GraphPlot.ji.   
Stacktrace: 
[1] compilecache(::String) at .\loading.jl:703    
[2] _require(::Symbol) at .\loading.jl:490    
[3] require(::Symbol) at .\loading.jl:398         
```

Thanks!

**Comment by sbromberger** [comment]
Have you tried the latest master?

**Comment by AsileBcd** [comment]
I did not. Thank you it works now.
